branch-defaults:
  master:
    environment: LowCost-env
environment-defaults:
  LowCost-env:
    branch: null
    repository: null
global:
  application_name: koala_inspect
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js running
    on 64bit Amazon Linux/4.1.1
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
